### ISSUE TITLE
Getting tag value from array

### ISSUE THREAD

**Issue by kahwooi** [eumes/ber-tlv#6]
How can I get the Tag 57 and it's value in string?

```
//primitives
var string = '570101';
var tlv = [];
try {
    tlv = TlvFactory.parse(string);
}
catch (error){
    //we use the partially parsed tlv and show an error message
    tlv = error.partialTlv;
    console.log(error.name);
    console.log(error.message);
}
```

**Comment by eumes** [comment]
After parsing the string you just iterate over the returned array and if its a primitive tag you can access everything as follows:

```
var tlvItem = tlv[i]

var tag = tlvItem.tag //already is a string
var value = tlvItem.value.toString('hex') //was a buffer, now converted to hex representation
```

For constructed items you have another array that you can iterate over again:

```
var items = tlvItem.items //array of tlv items again
```

**Comment by kahwooi** [comment]
I saw that you have another project called ber-tlv-annotations.

```
tlvs = TlvFactory.parse(tlv);
var lookups = registry.lookupAnnotations(tlvs);
```

The lookups is an array with more information? Any quick way to get the tag value?

**Comment by eumes** [comment]
I don't know what you are referring to as `value`. If you parse it you get the raw value for the tag. Depending on the tag this might have different meanings (also depending on the environment the tags are used in). The annotation project allows you to register some generic information about tags and map this automatically. I used this for a personal project in the EMV area.

**Comment by kahwooi** [comment]
Okay, Thanks for answering.
