### ISSUE TITLE
Asynchronous support

### ISSUE THREAD

**Issue by kahwooi** [eumes/ber-tlv#7]
Is the library support only synchronous function without any callback or promise?

```
const tlvFactory = require('ber-tlv').TlvFactory
let result = tlvFactory.parse(ctx.request.rawBody)
```

Can it cause blocking if the request is in thousands per second?

**Comment by eumes** [comment]
Hi, I don't think this will be any issue. The parsing itself is straight forward and there are no blocking operations ongoing (i.e. accessing i/o).
