### ISSUE TITLE
Support callback for partialTLV

### ISSUE THREAD

**Issue by kahwooi** [eumes/ber-tlv#8]
How can I ignore partial tlv because of PKCS7 padding?

Is there any callback, because I don't want to trigger catch error:

Can I do something like this:
```
  return new Promise(function(resolve, reject) {
      tlvFactory.parse(tlv, (err, result) => {
        if (err) resolve(err.partialTlv)
        resolve(result)
      })
    })
```

**Comment by eumes** [comment]
The library is mainly build to parse well formed tlv code. The `partialTlv` property is mainly there to debug the input and not to routinely throw unstructured code on it.
There are instances where parts of the PKCS7 padding could still be interpreted as valid tlv item.

My recommendation is to properly remove the PKCS7 (or any other than 0 padding) before feeding it to the parser.
